# Generated by Django 3.2.9 on 2021-11-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.IntegerField(),
        ),
    ]
