# Generated by Django 3.2.9 on 2021-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211117_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
