# Generated by Django 3.2.9 on 2021-11-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_review_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_detai',
        ),
    ]
