# Generated by Django 3.2.9 on 2022-01-02 05:01

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageinfo',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.db.models.fields.AutoField)),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('logo', models.ImageField(upload_to='images')),
                ('channelname', models.CharField(max_length=50, null=True)),
                ('subscriber', models.IntegerField()),
                ('content1', models.CharField(max_length=2000, null=True)),
                ('content2', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
