# Generated by Django 3.2.9 on 2022-01-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_pageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.pageinfo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.pageinfo'),
        ),
    ]
