# Generated by Django 3.2.9 on 2022-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220102_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageinfo',
            old_name='channelname',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(max_length=120),
        ),
    ]
