# Generated by Django 3.2.9 on 2022-01-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_rating_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionrating',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='languagerating',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='qualityrating',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='email',
        ),
    ]
