# Generated by Django 3.2.9 on 2022-01-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220116_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagerating',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='qualityrating',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
